version: "3.6"
services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    volumes:
      - ./data:/data/db
    ports:
      - '27012:27017'
    networks:
      - proxy-net
  
  # db:
  #   container_name: db
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1688XdAs
  #     MYSQL_DATABASE: master
  #     MYSQL_USER: web
  #     MYSQL_PASSWORD: 1688XdAs
  #   command: --init-file /data/application/init.sql
  #   volumes:
  #     - ./database:/var/lib/mysql
  #     #- ./init:/docker-entrypoint-initdb.d/:ro"  
  #     - ./init/init.sql:/data/application/init.sql    
  #       #   command: --init-file /data/application/init.sql
  # #   volumes:
  # #     - ./database/dbdata:/var/lib/mysql:rw
  # #     - ./database:/docker-entrypoint-initdb.d
  # #     - ./init.sql:/data/application/init.sql
  #   ports:
  #     - "3306:3306"
  # db:
  #   container_name: db
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1688XdAs
  #     MYSQL_DATABASE: master
  #     MYSQL_USER: web
  #     MYSQL_PASSWORD: 1688XdAs
  #   #command: --init-file /data/application/1.sql
  #   volumes:
  #     - ./database/dbdata:/var/lib/mysql:rw
  #     - ./init/init.sql:/docker-entrypoint-initdb.d/1.sql
  #     #- ./init/init.sql:/data/application/init.sql
  #     # - ./database:/var/lib/mysql
  #     #- ./init/init.sql:/docker-entrypoint-initdb.d/1.sql"      
  #   ports:
  #     - "3306:3306"

  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=master
      - MYSQL_USER=web
      - MYSQL_PASSWORD=1688XdAs
      - MYSQL_ROOT_PASSWORD=1688XdAs
      - TZ=Asia/Bangkok  # เพิ่ม TimeZone ที่นี่
    ports:
      - '3306:3306'
    #command: --init-file /data/application/1.sql
    volumes:
      - ./database:/var/lib/mysql
      # - ./database:/docker-entrypoint-initdb.d
      - ./init:/docker-entrypoint-initdb.d"  
      #- ./init/1.sql:/data/application/1.sql
      #- ./database/1.sql:/docker-entrypoint-initdb.d/1.sql
      #- ./database/2.sql:/docker-entrypoint-initdb.d/2.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - proxy-net
 


  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1688XdAs
    ports:
      - "8181:80"
    networks:
     - proxy-net

 
  
  redis:
    image: redis
    restart: always
    ports:
      - 6178:6379
    volumes:
      - cache:/data
    entrypoint: redis-server --appendonly yes
    networks:
     - proxy-net

  with-pw:
    image: redis
    restart: always
    ports:
      - 6179:6379
    volumes:
      - cache:/data
    env_file: .env
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
     - proxy-net


# https:
#   image: caddy
#   container_name: https
#   ports:
#     - 80:80
#     - 443:443
#   environment:
#     - URL_DOMAIN='https://callback.sunshine.com'
#     - URL_DBDOMAIN='https://db.sunshine.com'
#   networks:
#     - proxy-net
#   volumes:
#     - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  proxy-net:
    name: app-net
    external: true

volumes:
  database:
    driver: local
  cache:
    driver: local
 