version: "3.3"
 
services:

  # apigateway:
  #   container_name: api_gateway
  #   build:
  #     context: ./apigateway
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - "4005:8050"
  #   env_file: .env
  #   # environment:
  #   #   - VIRTUAL_HOST=stagging.tsxbet.com
  #   #   - VIRTUAL_PORT=4007
  #   volumes:
  #     - ./apigateway/:/app
  #   networks:
  #       - proxy-net

  whoami2:
    image: traefik/whoami
    networks:
      - proxy-net
    labels:
      caddy: whoami2.paribrand.shop
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

  games:
    container_name: games
    build:
        context: ./games
        dockerfile: ./Dockerfile
        target: development
    volumes:
        - ./games:/app
        - /app/node_modules
        #- /app/.next
    expose:
        - '5003'
    ports:
        - "5003:5003"
    working_dir: /app
    env_file: .env
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=development

  zookeep:
    container_name: zookeep
    build:
        context: ./zookeep
        dockerfile: ./Dockerfile
        target: development
    volumes:
        - ./zookeep:/app
        - /app/node_modules
        #- /app/.next
    expose:
        - '4002'
    ports:
        - "4002:4002"
    working_dir: /app
    env_file: .env
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=development
    # labels:
    #   caddy: paribrand.shop
    #   caddy.reverse_proxy: "{{upstreams 4001}}"
    #   caddy.tls: "internal"
    # environment:
    #    - VIRTUAL_HOST=dashboard.tsxbet.com
    #    - VIRTUAL_PORT=4001
    #    - NEXT_PUBLIC_PREFIX=PKD
    networks:
        - proxy-net

  frontend_admin:
    container_name: frontend_admin
    build:
        context: ./frontend_admin
        dockerfile: ./Dockerfile
        target: development
    volumes:
        - ./frontend_admin:/app
        - /app/node_modules
        #- /app/.next
    expose:
        - '5001'
    ports:
        - "5001:5001"
    working_dir: /app
    env_file: .env
    # labels:
    #   caddy: paribrand.shop
    #   caddy.reverse_proxy: "{{upstreams 4001}}"
    #   caddy.tls: "internal"
    # environment:
    #    - VIRTUAL_HOST=dashboard.tsxbet.com
    #    - VIRTUAL_PORT=4001
    #    - NEXT_PUBLIC_PREFIX=PKD
    networks:
        - proxy-net

  gameservice:
    #image: king_game_service                                                                                                                                        
    container_name: game_service
    build:
      context: ./gameservice
      dockerfile: dev.Dockerfile
    ports:
      - "4007:8070"
    env_file: .env
    # environment:
    #   - VIRTUAL_HOST=games.tsxbet.com
    #   - VIRTUAL_PORT=4007
    volumes:
      - ./gameservice/:/app
    networks:
        - proxy-net



  gservice:
    # image: gclub
    build:
      context: ./gclubservice
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./gclubservice/src:/home/node/app/src
      - ./gclubservice/nodemon.json:/home/node/app/nodemon.json
    container_name: gservice
    expose:
      - '9003'
    ports:
      - '9003:9003'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: " npm run dev"
    # environment:
    #   - VIRTUAL_HOST=gclub.tsxbet.net
    #   - VIRTUAL_PORT=3003
    env_file: .env
    networks:
      - proxy-net

  backendservice:
    image: king_backend_service
    container_name: backend_service
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "4006:8060"
    env_file: .env
    # environment:
    #   - VIRTUAL_HOST=stagging.tsxbet.com
    #   - VIRTUAL_PORT=4007
    volumes:
      - ./backend/:/app
    networks:
        - proxy-net


networks:
  proxy-net:
      name: app-net
      external: true
  # caddy:
  #     external: true